### ISSUE TITLE
Wiremod Incompatibility?

### ISSUE THREAD

**Issue by TwistedTail** [nedhyett/Vermilion#107] opened 2015-04-23 23:37 UTC
[Vermilion 2] lua/vermilion2/modules/event_logger/init.lua:139: attemp to index a nil value
  1. hookFunc - lua/vermilion2/modules/event_logger/init.lua:139
    2. unknown - lua/vermilion2/shared.lua:210

[Vermilion 2] lua/vermilion2/modules/event_logger/init.lua:147: attemp to index a nil value
  1. hookFunc - lua/vermilion2/modules/event_logger/init.lua:147
    2. unknown - lua/vermilion2/shared.lua:210

Happens in Multiplayer, when trying to activate a Pod Controller. It disables the Pod Controllers.

http://prntscr.com/6xfekc

I do really like this addon, but it has been giving a lot of problems this time.

**Comment by nedhyett** [comment] 2015-04-24 10:34
Just disable the event logger until I can get it fixed.

**Comment by nedhyett** [comment] 2015-04-24 14:34
Sorry about the snappy reply. I was at college and I just realised that I had run out of time as I was writing that comment.

It's not an incompatibility, it's just a bug that was caused by Wiremod calling a hook in a way that I didn't expect it to. The documentation on the GMod wiki is very vague and doesn't discuss all of the possible ways people can use things (~40% of the documentation is actually incomplete).

Bugs like this will happen with any piece of software, and the only reason they still exist in Vermilion is because people are not reporting them to me so I can fix them. I learned this the hard way when I used to play Minecraft, where a common phrase was "Stack trace or GTFO", which, to put it more politely is "Stack trace or the error didn't happen". I cant' fix things unless they are reported, and I must thank you for actually taking the time to help me fix these problems.

**Comment by nedhyett** [comment] 2015-04-24 15:11
This will be fixed in the 2.5 release. However this release is very far from being workshop ready, so the only way to use it would be to download the source and place it in the addons folder of your server. It's also probably too buggy for production use yet.

**Closed by nedhyett** 2015-04-24 15:11 UTC
Labels: bug, crossmod
